#include "ft_isalpha_test.cc"
#include "ft_isdigit_test.cc"
#include "ft_isalnum_test.cc"
#include "ft_isascii_test.cc"
#include "ft_isprint_test.cc"
#include "ft_strlen_test.cc"
#include "ft_memset_test.cc"
#include "ft_bzero_test.cc"
